### ISSUE TITLE
Cannot resume after M6-triggered pause from tablet pendant

### ISSUE THREAD

**Issue by Billiam** [cncjs/cncjs-shopfloor-tablet#24]
If I pause a running job manually, either from the shopfloor tablet interface or the main cncjs interface, the tablet mode changes to a paused state (so that the control buttons  change to 'resume' and 'stop').

If that pause is instead caused by an M6 toolchange, the main cncjs interface's buttons correctly change to the paused state, showing resume and stop, but the tablet UI's buttons do not, instead displaying "Start" and "Pause" (with pause disabled), as if a job was not in progress.

If I load the following gcode file:
```
T3 M6
```

I can see the following in the websocket logs in dev tools in the tablet UI:
```
["workflow:state","running"]
["workflow:state","paused"]
["feeder:status",{"hold":false,"holdReason":null,"queue":0,"pending":false,"changed":false}]
["sender:status",{"sp":1,"hold":true,"holdReason":{"data":"M6"},"name":"m6","context":{...lots of context}]
```

but the tablet UI state will be incorrect.

**Versions**
CNCjs: 1.9.22
Node.js: 10.19.0
NPM: 6.14.4

Grbl + Raspberry Pi

**Comment by MitchBradley** [comment]
I fixed both M6 and M0.  Unlike the main UI, the tablet UI synchronizes the messaging so the M6 notification does not appear until the machine has actually reached the M6 point after executing the preceding GCode.  The tool number can be seen in the highlighted GCode line.   The UI also works with M0 and M1, although M0 can result in the highlighted line being off by one, due to removal of the M0 line from the GCode that is transmitted to the controller (that removal is not under UI control).
